# Generated by Django 5.0.9 on 2024-12-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', help_text='Current status of the notification task', max_length=10)),
                ('content', models.JSONField(help_text="JSON containing notification details: 'to', 'subject', message' ")),
                ('retry', models.PositiveIntegerField(default=0, help_text='Number of retry attempts made for this notification')),
                ('type', models.CharField(help_text='Platform through which we want to send the data ', verbose_name=[('email', 'Email'), ('whatsapp', 'Whatsapp')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='notification_task',
        ),
    ]
