# Generated by Django 5.0.9 on 2024-12-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_notificationtask_delete_notification_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtask',
            name='is_active',
        ),
    ]
