# Generated by Django 5.0.9 on 2024-12-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_notificationtask_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtask',
            name='source',
            field=models.CharField(choices=[('flights', 'Flights'), ('helpdesk', 'HelpDesk'), ('accounts', 'Accounts')], default='Flights', help_text='From which service this notification request is coming ', max_length=20),
            preserve_default=False,
        ),
    ]
