# Generated by Django 5.0.9 on 2024-12-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_notificationtask_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtask',
            name='taskName',
            field=models.TextField(choices=[('create ticket', 'create ticket'), ('send otp', 'send otp'), ('register complaint', 'register complaint')], default='create ticket', help_text='Exactly what are we supposed to do'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationtask',
            name='source',
            field=models.CharField(choices=[('flights', 'Flights'), ('helpdesk', 'HelpDesk'), ('accounts', 'Accounts')], help_text='From which service this notification request is coming', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtask',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('success', 'Sent'), ('failed', 'Failed')], default='queued', help_text='Current status of the notification task', max_length=10),
        ),
    ]
